#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require './AdventOfCodeCommand.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new AdventOfCodeCommand());

$application->run();
